baseURL = "https://www.reidw.me"
languageCode = "en-us"
title = "Made"
theme = "PaperMod"
publishDir = "reidwilliams.github.io"
Paginate = 20

[params]
  disableThemeToggle = true
  disableSpecial1stPost = false
