baseURL = "https://made.reidw.co"
languageCode = "en-us"
title = "Made"
theme = "PaperMod"
publishDir = "reidwilliams.github.io"
Paginate = 20

[params]
  disableThemeToggle = true
  disableSpecial1stPost = false
